name: MacOS
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew update
          brew install ninja
          brew install doxygen graphviz
      - name: Configure
        shell: bash
        run: cmake -B ${{github.workspace}}/build --preset="dev-debug" -G "Ninja"
      - name: Build
        shell: bash
        run: cmake --build ${{github.workspace}}/build
      - name: Test
        shell: bash
        run: |
          cd ${{github.workspace}}/build
          ctest -V
      - name: Generate Documentation
        shell: bash
        run: ${{github.workspace}}/scripts/gendocs.sh
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ github.workspace }}/docs/package-lock.json
      - name: Build VitePress site
        working-directory: ${{ github.workspace }}/docs
        run: npm ci && npm run build
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/docs/.vitepress/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4