name: Ubuntu
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get -yq update
          sudo apt-get install -yq cmake ninja-build libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config doxygen graphviz g++-14
          gcc --version
      - name: Configure
        shell: bash
        env:
          CC: gcc-14
          CXX: g++-14
        run: cmake -B ${{github.workspace}}/build --preset="dev-debug" -G "Ninja"
      - name: Build
        shell: bash
        run: cmake --build ${{github.workspace}}/build
      - name: Test
        shell: bash
        run: |
          cd ${{github.workspace}}/build
          ctest -V